# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseNotify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBaseNotify
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Alamofire'
  pod 'ObjectMapper'
end
